services:
  mongo:
    image: mongo:7
    container_name: imperio_agua_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    container_name: imperio_agua_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/.env:/app/.env
    depends_on:
      - mongo
volumes:
  mongo_data:
